name: vgv_assessment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.2
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod: ^2.6.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  checks: ^0.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
